### ISSUE TITLE
How to change the shortcut?

### ISSUE THREAD

**Issue by buremba** [amiechen/pretzel#1]
I use the shortcut `CmdorCtrl + (backtick)` for changing the windows of the same application and Pretzel broke that shortcut. How can make configure the shortcut used by Pretzel?

**Comment by cucumbur** [comment]
Came here to report this issue. Its the default macOS shortcut and I use it on nearly every program.

**Comment by cucumbur** [comment]
I can fork and make a simple changed shortcut to something that doesn't conflict with known shortcuts, or even try to contribute substantially by studying the architecture and fitting a minimalist change hotkey widget in it somewhere without making it complex. It could just be a right click / control click feature.

**Comment by cucumbur** [comment]
https://github.com/cucumbur/pretzel
My fork fixes this by making the shortcut Cmd + Alt/Opt + Shift + P, as a temporary fix. Haven't had time to reinstall npm to fix the build errors im getting though so no binaries.

**Comment by amiechen** [comment]
Thanks for the good suggestions @buremba @cucumbur! I will make the shortcut customizable and let you knwo when it's out.
