### ISSUE TITLE
CtrlOrCmd?

### ISSUE THREAD

**Issue by LucaRosaldi** [amiechen/pretzel#12]
Hi,

in the Shortcut column on the right, i find the word **"CtrlOrCmd"** somewhat confusing, adding a little bit of cognitive load each time I use the app. And, being Pretzel a Mac only app, I’m not sure why the "Ctrl" is even displayed.

i.e. in Chrome, the "Open a new window" shortcut is listed as "CtrlOrCmd + n". On Mac Os, `Ctrl + n` doesn’t do anything – the right one is `Cmd + N`.

**Comment by amiechen** [comment]
@LucaRosaldi Good point! I agree too. It was based on the plan that the app would work in all Windows/Linux/Mac, though currently only open to Mac. 

I'm thinking to swap Cmd/Ctrl when packaging for different platforms, which would solve for this usability issues. I've added a todo in the roadmap https://github.com/amiechen/pretzel/projects/1
