### ISSUE TITLE
Support symbols instead of text

### ISSUE THREAD

**Issue by jwkicklighter** [amiechen/pretzel#20]
Would be nice to support Cmd/Opt/Ctrl/Shift icons instead of having to read the words.

**Comment by amiechen** [comment]
thanks! this was a decision after some considerations about user experience. Not everyone is familiar with the symbols but everyone can understand the text. Eventhough it takes up more space and more verbose, I believe it's less ambiguous. Hope it answer your questions!

**Comment by jwkicklighter** [comment]
I don't know that I really agree since this is a bit of a power user tool anyway. Even the default MacOS UI uses symbols instead of text.

At the very least it could be an option. Because on the flip side, I find that it takes more mental energy to read the words instead of symbols.
