### ISSUE TITLE
Doesn't work for PhpStorm

### ISSUE THREAD

**Issue by ozgurkaragoz** [amiechen/pretzel#23]
Hi,

I use PhpStorm on OSX but this app does not work. When i checked the repository, then i saw PHPStorm.yml file is exists in "shortcuts" at folder.

Could it be a problem with the program's name? Because file name is "PHPStorm" in repository, but program's real name is "PhpStorm".

![Screen Shot 2019-04-15 at 10 01 17](https://user-images.githubusercontent.com/6477375/56113064-6e659f00-5f65-11e9-8736-4a6c85eda9d2.png)

**Comment by amiechen** [comment]
I bet you are right - feel free to do a PR after testing it locally I'll merge it in. thanks!

**Comment by ozgurkaragoz** [comment]
I have tested and it does work! Pull request: https://github.com/amiechen/pretzel/pull/24

**Comment by amiechen** [comment]
Thank you! Merged
