### ISSUE TITLE
We should figure out how cheatsheet work

### ISSUE THREAD

**Issue by tangxuan** [amiechen/pretzel#25]
I like your idea for searching. And I think Cheatsheet get all shortcuts programmely. So let's figure it out, and the repo will be more powerful.

**Comment by amiechen** [comment]
Not an issue so closing this, though I agree what you said. Cheatsheet is probably using Apple's accessibility api to get the shortcuts, and I'd love to see if there's a possibility to tap into that for Pretzel too. Feel free to do a PR, thanks!
