### ISSUE TITLE
Link to supported apps page is incorrect

### ISSUE THREAD

**Issue by thejasonparker** [amiechen/pretzel#27]
**Describe the bug**
When I click on the supported apps link which is the four squares icon in the top left corner it takes me to this URL which generates a 404 error....

https://www.amie-chen.com/pretzel/supported-apps/

**To Reproduce**
1. Click on the pretzel men icon
2. Click on the four squares icon in the top left corner

**Expected behavior**
Link should go to this url...
https://pretzel.amie-chen.com/supported-apps

**Desktop (please complete the following information):**
 - OS: OS X Mojave
 - Version 10.14.4 (18E226)

**Comment by amiechen** [comment]
Fixed and deployed. Thanks @thejasonparker !
