### ISSUE TITLE
如何修改快捷键

### ISSUE THREAD

**Issue by xiaochunjimmy** [amiechen/pretzel#8]
我发现Pretzel使用的快捷键是`⌘+~`，但这个快捷键我之前主要用于切换同一个App的不同窗口，比如我会同时打开多个浏览器窗口，多个Sketch文件等等，用这个快捷键来切换，但现在这个快捷键被Pretzel占用了，我如何修改快捷键呢？

**Comment by amiechen** [comment]
Hi @xiaochunjimmy I just published a patch which allows uers to customize shortcuts. Let me know if you still have issues after installing the new updates (if new updates doesn't work, please download it from [here](amie-chen.com/pretzel))
